name: publish

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: NutritionCalc.Web
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Set this to the path to your web app project, defaults to the repository root:
  DOTNET_VERSION: '7.0.101' # The .NET SDK version to use

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install dependencies
      run: |
        cd NutritionCalc.Web
        dotnet restore
    
    - name: Build
      run: |
        cd NutritionCalc.Web
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o release –nologo
   
    - name: Publish .NET Core Project
      run: dotnet publish NutritionCalc.Web.csproj -c Release -o release –nologo
    
    - name: Change base-tag in index.html
      run: sed -i ‘s/<base href=”\/” \/>/<base href=”\/NutritionCalc.Web\/” \/>/g’ release/wwwroot/index.html
      
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - uses: JamesIves/github-pages-deploy-action@3.7.1
      name: Commit wwwroot to GitHub pages
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
