name: publish

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: NutritionCalc.Web
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Set this to the path to your web app project, defaults to the repository root:
  DOTNET_VERSION: '7.0.101' # The .NET SDK version to use

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install dependencies
      run: |
        cd NutritionCalc.Web
        dotnet restore
    
    - name: Build
      run: |
        cd NutritionCalc.Web
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o release
    
    - name: Change base-tag in index.html
      run: |
        cd NutritionCalc.Web/release/wwwroot
        dir
        sed -i 's/<base href=”\/” \/>/<base href=”\/NutritionCalc.Web\/” \/>/g' index.html
